site_name: My Study Decks
site_url: https://rajdyp.github.io/my-study-decks/

nav:
- Home: index.md
- AWS:
    - Fundamentals Series:
        - Linux Basics:
            - Introduction: level101/linux_basics/intro.md
            - Command Line Basics: level101/linux_basics/command_line_basics.md
            - Server Administration: level101/linux_basics/linux_server_administration.md
            - Conclusion: level101/linux_basics/conclusion.md
        - Git:
            - Git Basics: level101/git/git-basics.md
            - Working With Branches: level101/git/branches.md
            - Github and Hooks: level101/git/github-hooks.md
            - Conclusion: level101/git/conclusion.md
        - Linux Networking:
            - Introduction: level101/linux_networking/intro.md
            - DNS: level101/linux_networking/dns.md
            - UDP: level101/linux_networking/udp.md
            - HTTP: level101/linux_networking/http.md
            - TCP: level101/linux_networking/tcp.md
            - Routing: level101/linux_networking/ipr.md
            - Conclusion: level101/linux_networking/conclusion.md
  - Python:
    - Fundamentals Series:
        - Linux Basics:
            - Introduction: level101/linux_basics/intro.md
            - Command Line Basics: level101/linux_basics/command_line_basics.md
            - Server Administration: level101/linux_basics/linux_server_administration.md
            - Conclusion: level101/linux_basics/conclusion.md
            
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/rajdyp"  target="_blank" rel="noopener">Rajdeep Rai</a>
