site_name: My Study Decks
site_url: https://rajdyp.github.io/my-study-decks/

nav:
- Home: index.md
- AWS:
    - Fundamentals Series:
        - Linux Basics:
            - Introduction: aws.md
            - Command Line Basics: test.md
  - Python:
    - Fundamentals Series:
        - Linux Basics:
            - Introduction: python_for_coding_interviews.md
            - Command Line Basics: est.md
            
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/rajdyp"  target="_blank" rel="noopener">Rajdeep Rai</a>
